BEGIN;


/*
 * ============================================================
 * CÔNG VIỆC
 * ============================================================
 */

CREATE TABLE cong_viec (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nguoi_dung_id INTEGER,
    phien_khach_id INTEGER,


    request_id UUID NOT NULL DEFAULT gen_random_uuid(),
    khoa_idempotency VARCHAR(128),

    loai_cong_viec VARCHAR(50) NOT NULL,
    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_XU_LY',

    muc_do_uu_tien SMALLINT NOT NULL DEFAULT 5,

    tien_trinh NUMERIC(5,2) NOT NULL DEFAULT 0,
    buoc_hien_tai VARCHAR(255),

    tep_nguon_id INTEGER,
    phien_ban_nguon_id INTEGER,
    tep_ket_qua_id INTEGER,
    phien_ban_ket_qua_id INTEGER,

    dinh_dang_nguon VARCHAR(50),
    dinh_dang_dich VARCHAR(50),

    dau_vao JSONB NOT NULL DEFAULT '{}'::JSONB,
    tuy_chon JSONB NOT NULL DEFAULT '{}'::JSONB,
    dau_ra JSONB NOT NULL DEFAULT '{}'::JSONB,

    queue_name VARCHAR(100),
    queue_job_id VARCHAR(255),

    so_lan_thu INTEGER NOT NULL DEFAULT 0,
    so_lan_thu_toi_da INTEGER NOT NULL DEFAULT 3,

    ma_loi VARCHAR(100),
    thong_bao_loi TEXT,
    chi_tiet_loi JSONB,

    xep_hang_luc TIMESTAMPTZ,
    bat_dau_luc TIMESTAMPTZ,
    hoan_thanh_luc TIMESTAMPTZ,
    huy_luc TIMESTAMPTZ,

    het_han_luc TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_cong_viec_nguoi_dung
        FOREIGN KEY (
            nguoi_dung_id
        )
        REFERENCES nguoi_dung (
            id
        )
        ON DELETE SET NULL,

    CONSTRAINT fk_cong_viec_tep_nguon
        FOREIGN KEY (
            tep_nguon_id
        )
        REFERENCES tep (
            id
        )
        ON DELETE SET NULL,

    CONSTRAINT fk_cong_viec_phien_ban_nguon
        FOREIGN KEY (
            phien_ban_nguon_id
        )
        REFERENCES phien_ban_tep (
            id
        )
        ON DELETE SET NULL,

    CONSTRAINT fk_cong_viec_tep_ket_qua
        FOREIGN KEY (
            tep_ket_qua_id
        )
        REFERENCES tep (
            id
        )
        ON DELETE SET NULL,

    CONSTRAINT fk_cong_viec_phien_ban_ket_qua
        FOREIGN KEY (
            phien_ban_ket_qua_id
        )
        REFERENCES phien_ban_tep (
            id
        )
        ON DELETE SET NULL,

    CONSTRAINT chk_cong_viec_chu_so_huu
        CHECK (
            NOT (
                nguoi_dung_id IS NOT NULL
                AND phien_khach_id IS NOT NULL
            )
        ),

    CONSTRAINT chk_cong_viec_trang_thai
        CHECK (
            trang_thai IN (
                'CHO_XU_LY',
                'DANG_PHAN_TICH',
                'DANG_XU_LY',
                'DANG_CHUYEN_DOI',
                'DANG_KET_XUAT',
                'DANG_OCR',
                'DANG_DICH',
                'HOAN_THANH',
                'THAT_BAI',
                'DANG_HUY',
                'DA_HUY'
            )
        ),

    CONSTRAINT chk_cong_viec_uu_tien
        CHECK (
            muc_do_uu_tien BETWEEN 1 AND 10
        ),

    CONSTRAINT chk_cong_viec_tien_trinh
        CHECK (
            tien_trinh BETWEEN 0 AND 100
        ),

    CONSTRAINT chk_cong_viec_so_lan_thu
        CHECK (
            so_lan_thu >= 0
            AND so_lan_thu_toi_da >= 0
        ),

    CONSTRAINT uq_cong_viec_request_id
        UNIQUE (
            request_id
        )
);


CREATE UNIQUE INDEX uq_cong_viec_idempotency_nguoi_dung
ON cong_viec (
    nguoi_dung_id,
    khoa_idempotency
)
WHERE nguoi_dung_id IS NOT NULL
AND khoa_idempotency IS NOT NULL;


CREATE UNIQUE INDEX uq_cong_viec_idempotency_khach
ON cong_viec (
    phien_khach_id,
    khoa_idempotency
)
WHERE phien_khach_id IS NOT NULL
AND khoa_idempotency IS NOT NULL;


CREATE INDEX idx_cong_viec_trang_thai
ON cong_viec (
    trang_thai,
    muc_do_uu_tien DESC,
    created_at ASC
);


CREATE INDEX idx_cong_viec_nguoi_dung
ON cong_viec (
    nguoi_dung_id,
    created_at DESC
)
WHERE nguoi_dung_id IS NOT NULL;


CREATE INDEX idx_cong_viec_phien_khach
ON cong_viec (
    phien_khach_id,
    created_at DESC
)
WHERE phien_khach_id IS NOT NULL;


CREATE INDEX idx_cong_viec_queue
ON cong_viec (
    queue_name,
    queue_job_id
)
WHERE queue_job_id IS NOT NULL;


CREATE INDEX idx_cong_viec_tep_nguon
ON cong_viec (
    tep_nguon_id
)
WHERE tep_nguon_id IS NOT NULL;


CREATE INDEX idx_cong_viec_tep_ket_qua
ON cong_viec (
    tep_ket_qua_id
)
WHERE tep_ket_qua_id IS NOT NULL;


CREATE INDEX idx_cong_viec_het_han
ON cong_viec (
    het_han_luc
)
WHERE het_han_luc IS NOT NULL;


CREATE TRIGGER trg_cong_viec_updated_at
BEFORE UPDATE
ON cong_viec
FOR EACH ROW
EXECUTE FUNCTION fn_cap_nhat_updated_at();


/*
 * ============================================================
 * LIÊN KẾT PHIÊN BẢN TỆP → CÔNG VIỆC
 * ============================================================
 */

ALTER TABLE phien_ban_tep
ADD CONSTRAINT fk_phien_ban_tep_cong_viec_tao
FOREIGN KEY (
    cong_viec_tao_id
)
REFERENCES cong_viec (
    id
)
ON DELETE SET NULL;


COMMIT;