BEGIN;


/*
 * ============================================================
 * BƯỚC CÔNG VIỆC
 * ============================================================
 */

CREATE TABLE buoc_cong_viec (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cong_viec_id INTEGER NOT NULL,

    thu_tu INTEGER NOT NULL,

    ma_buoc VARCHAR(100) NOT NULL,
    ten_buoc VARCHAR(255) NOT NULL,
    loai_buoc VARCHAR(50) NOT NULL,

    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_XU_LY',

    tien_trinh NUMERIC(5,2) NOT NULL DEFAULT 0,

    bat_buoc BOOLEAN NOT NULL DEFAULT TRUE,

    queue_name VARCHAR(100),
    queue_job_id VARCHAR(255),

    bo_xu_ly VARCHAR(255),
    cong_cu VARCHAR(100),
    phien_ban_cong_cu VARCHAR(100),

    dau_vao JSONB NOT NULL DEFAULT '{}'::JSONB,
    tuy_chon JSONB NOT NULL DEFAULT '{}'::JSONB,
    dau_ra JSONB NOT NULL DEFAULT '{}'::JSONB,
    thong_ke JSONB NOT NULL DEFAULT '{}'::JSONB,

    so_lan_thu INTEGER NOT NULL DEFAULT 0,
    so_lan_thu_toi_da INTEGER NOT NULL DEFAULT 1,

    ma_loi VARCHAR(100),
    thong_bao_loi TEXT,
    chi_tiet_loi JSONB,

    bat_dau_luc TIMESTAMPTZ,
    hoan_thanh_luc TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_buoc_cong_viec_cong_viec
        FOREIGN KEY (
            cong_viec_id
        )
        REFERENCES cong_viec (
            id
        )
        ON DELETE CASCADE,

    CONSTRAINT chk_buoc_cong_viec_thu_tu
        CHECK (
            thu_tu > 0
        ),

    CONSTRAINT chk_buoc_cong_viec_trang_thai
        CHECK (
            trang_thai IN (
                'CHO_XU_LY',
                'DANG_XU_LY',
                'HOAN_THANH',
                'THAT_BAI',
                'BO_QUA',
                'DA_HUY'
            )
        ),

    CONSTRAINT chk_buoc_cong_viec_tien_trinh
        CHECK (
            tien_trinh BETWEEN 0 AND 100
        ),

    CONSTRAINT chk_buoc_cong_viec_so_lan_thu
        CHECK (
            so_lan_thu >= 0
            AND so_lan_thu_toi_da >= 0
        ),

    CONSTRAINT uq_buoc_cong_viec_thu_tu
        UNIQUE (
            cong_viec_id,
            thu_tu
        )
);


CREATE INDEX idx_buoc_cong_viec_cong_viec
ON buoc_cong_viec (
    cong_viec_id,
    thu_tu
);


CREATE INDEX idx_buoc_cong_viec_trang_thai
ON buoc_cong_viec (
    trang_thai
);


CREATE INDEX idx_buoc_cong_viec_queue
ON buoc_cong_viec (
    queue_name,
    queue_job_id
)
WHERE queue_job_id IS NOT NULL;


CREATE TRIGGER trg_buoc_cong_viec_updated_at
BEFORE UPDATE
ON buoc_cong_viec
FOR EACH ROW
EXECUTE FUNCTION fn_cap_nhat_updated_at();


COMMIT;