BEGIN;


/*
 * ============================================================
 * ĐĂNG KÝ GÓI
 * ============================================================
 */

CREATE TABLE dang_ky_goi (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nguoi_dung_id INTEGER NOT NULL,
    goi_dich_vu_id INTEGER NOT NULL,

    trang_thai VARCHAR(30) NOT NULL DEFAULT 'CHO_THANH_TOAN',

    nguon_kich_hoat VARCHAR(30) NOT NULL DEFAULT 'THANH_TOAN',

    gia_thanh_toan NUMERIC(18,2) NOT NULL DEFAULT 0,
    tien_te VARCHAR(3) NOT NULL DEFAULT 'VND',

    ma_giao_dich VARCHAR(255),

    bat_dau_luc TIMESTAMPTZ,
    het_han_luc TIMESTAMPTZ,

    huy_luc TIMESTAMPTZ,

    tu_dong_gia_han BOOLEAN NOT NULL DEFAULT FALSE,

    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_dang_ky_goi_nguoi_dung
        FOREIGN KEY (
            nguoi_dung_id
        )
        REFERENCES nguoi_dung (
            id
        )
        ON DELETE CASCADE,

    CONSTRAINT fk_dang_ky_goi_goi
        FOREIGN KEY (
            goi_dich_vu_id
        )
        REFERENCES goi_dich_vu (
            id
        )
        ON DELETE RESTRICT,

    CONSTRAINT chk_dang_ky_goi_trang_thai
        CHECK (
            trang_thai IN (
                'CHO_THANH_TOAN',
                'HOAT_DONG',
                'TAM_DUNG',
                'HET_HAN',
                'DA_HUY'
            )
        ),

    CONSTRAINT chk_dang_ky_goi_nguon
        CHECK (
            nguon_kich_hoat IN (
                'THANH_TOAN',
                'QUAN_TRI',
                'KHUYEN_MAI',
                'HE_THONG'
            )
        ),

    CONSTRAINT chk_dang_ky_goi_gia
        CHECK (
            gia_thanh_toan >= 0
        ),

    CONSTRAINT chk_dang_ky_goi_tien_te
        CHECK (
            tien_te ~ '^[A-Z]{3}$'
        ),

    CONSTRAINT chk_dang_ky_goi_thoi_gian
        CHECK (
            het_han_luc IS NULL
            OR bat_dau_luc IS NULL
            OR bat_dau_luc < het_han_luc
        )
);


CREATE UNIQUE INDEX uq_dang_ky_goi_dang_hoat_dong
ON dang_ky_goi (
    nguoi_dung_id
)
WHERE trang_thai = 'HOAT_DONG';


CREATE INDEX idx_dang_ky_goi_nguoi_dung
ON dang_ky_goi (
    nguoi_dung_id,
    created_at DESC
);


CREATE INDEX idx_dang_ky_goi_goi
ON dang_ky_goi (
    goi_dich_vu_id,
    trang_thai
);


CREATE INDEX idx_dang_ky_goi_het_han
ON dang_ky_goi (
    het_han_luc
)
WHERE trang_thai = 'HOAT_DONG'
AND het_han_luc IS NOT NULL;


CREATE TRIGGER trg_dang_ky_goi_updated_at
BEFORE UPDATE
ON dang_ky_goi
FOR EACH ROW
EXECUTE FUNCTION fn_cap_nhat_updated_at();


COMMIT;