BEGIN;


/*
 * ============================================================
 * PHIÊN ĐĂNG NHẬP
 * ============================================================
 */

CREATE TABLE phien_dang_nhap (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nguoi_dung_id INTEGER NOT NULL,
    jti UUID NOT NULL,

    refresh_token_hash CHAR(64) NOT NULL,

    dia_chi_ip INET,
    user_agent VARCHAR(1000),

    het_han_luc TIMESTAMP WITH TIME ZONE NOT NULL,
    su_dung_lan_cuoi_luc TIMESTAMP WITH TIME ZONE,

    vo_hieu_hoa_luc TIMESTAMP WITH TIME ZONE,
    ly_do_vo_hieu_hoa VARCHAR(255),

    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_phien_dang_nhap_nguoi_dung
        FOREIGN KEY (nguoi_dung_id)
        REFERENCES nguoi_dung(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_phien_dang_nhap_jti
        UNIQUE (jti),

    CONSTRAINT uq_phien_dang_nhap_refresh_token_hash
        UNIQUE (refresh_token_hash),

    CONSTRAINT chk_phien_dang_nhap_het_han
        CHECK (het_han_luc > created_at)
);


CREATE INDEX idx_phien_dang_nhap_nguoi_dung
ON phien_dang_nhap(nguoi_dung_id);


CREATE INDEX idx_phien_dang_nhap_nguoi_dung_hoat_dong
ON phien_dang_nhap(nguoi_dung_id, het_han_luc)
WHERE vo_hieu_hoa_luc IS NULL;


CREATE INDEX idx_phien_dang_nhap_het_han
ON phien_dang_nhap(het_han_luc);


CREATE TRIGGER trg_phien_dang_nhap_updated_at
BEFORE UPDATE ON phien_dang_nhap
FOR EACH ROW
EXECUTE FUNCTION fn_cap_nhat_updated_at();


COMMIT;