--
-- PostgreSQL database dump
--

\restrict Om8VEeVKmnGBcOmNUgdNyEHFm7O67qxv3Hb05q2OqwDNix1CfdD1Kc0MWud6bJU

-- Dumped from database version 18.6 (Postgres.app)
-- Dumped by pg_dump version 18.6 (Postgres.app)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: fn_cap_nhat_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fn_cap_nhat_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();

    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: buoc_cong_viec; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.buoc_cong_viec (
    id integer NOT NULL,
    cong_viec_id integer NOT NULL,
    thu_tu integer NOT NULL,
    ma_buoc character varying(100) NOT NULL,
    ten_buoc character varying(255) NOT NULL,
    loai_buoc character varying(50) NOT NULL,
    trang_thai character varying(30) DEFAULT 'CHO_XU_LY'::character varying NOT NULL,
    tien_trinh numeric(5,2) DEFAULT 0 NOT NULL,
    bat_buoc boolean DEFAULT true NOT NULL,
    queue_name character varying(100),
    queue_job_id character varying(255),
    bo_xu_ly character varying(255),
    cong_cu character varying(100),
    phien_ban_cong_cu character varying(100),
    dau_vao jsonb DEFAULT '{}'::jsonb NOT NULL,
    tuy_chon jsonb DEFAULT '{}'::jsonb NOT NULL,
    dau_ra jsonb DEFAULT '{}'::jsonb NOT NULL,
    thong_ke jsonb DEFAULT '{}'::jsonb NOT NULL,
    so_lan_thu integer DEFAULT 0 NOT NULL,
    so_lan_thu_toi_da integer DEFAULT 1 NOT NULL,
    ma_loi character varying(100),
    thong_bao_loi text,
    chi_tiet_loi jsonb,
    bat_dau_luc timestamp with time zone,
    hoan_thanh_luc timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_buoc_cong_viec_so_lan_thu CHECK (((so_lan_thu >= 0) AND (so_lan_thu_toi_da >= 0))),
    CONSTRAINT chk_buoc_cong_viec_thu_tu CHECK ((thu_tu > 0)),
    CONSTRAINT chk_buoc_cong_viec_tien_trinh CHECK (((tien_trinh >= (0)::numeric) AND (tien_trinh <= (100)::numeric))),
    CONSTRAINT chk_buoc_cong_viec_trang_thai CHECK (((trang_thai)::text = ANY ((ARRAY['CHO_XU_LY'::character varying, 'DANG_XU_LY'::character varying, 'HOAN_THANH'::character varying, 'THAT_BAI'::character varying, 'BO_QUA'::character varying, 'DA_HUY'::character varying])::text[])))
);


--
-- Name: buoc_cong_viec_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.buoc_cong_viec ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buoc_cong_viec_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chinh_sach_han_muc; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chinh_sach_han_muc (
    id integer NOT NULL,
    ma character varying(100) NOT NULL,
    ten character varying(255) NOT NULL,
    doi_tuong character varying(30) NOT NULL,
    loai_tai_khoan character varying(30),
    goi_dich_vu_id integer,
    ma_hanh_dong character varying(50) NOT NULL,
    don_vi character varying(20) DEFAULT 'LAN'::character varying NOT NULL,
    chu_ky character varying(20) DEFAULT 'NGAY'::character varying NOT NULL,
    mui_gio character varying(64) DEFAULT 'UTC'::character varying NOT NULL,
    gioi_han bigint,
    khong_gioi_han boolean DEFAULT false NOT NULL,
    hanh_dong_khi_vuot character varying(30) DEFAULT 'TU_CHOI'::character varying NOT NULL,
    muc_do_uu_tien integer DEFAULT 100 NOT NULL,
    hieu_luc_tu timestamp with time zone DEFAULT now() NOT NULL,
    hieu_luc_den timestamp with time zone,
    active boolean DEFAULT true NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_chinh_sach_han_muc_chu_ky CHECK (((chu_ky)::text = ANY ((ARRAY['MOI_REQUEST'::character varying, 'MOI_TEP'::character varying, 'NGAY'::character varying, 'TUAN'::character varying, 'THANG'::character varying, 'THEO_GOI'::character varying, 'TOAN_THOI_GIAN'::character varying])::text[]))),
    CONSTRAINT chk_chinh_sach_han_muc_doi_tuong CHECK (((doi_tuong)::text = ANY ((ARRAY['KHACH'::character varying, 'NGUOI_DUNG'::character varying, 'LOAI_TAI_KHOAN'::character varying, 'GOI_DICH_VU'::character varying])::text[]))),
    CONSTRAINT chk_chinh_sach_han_muc_doi_tuong_chi_tiet CHECK (((((doi_tuong)::text = 'KHACH'::text) AND (loai_tai_khoan IS NULL) AND (goi_dich_vu_id IS NULL)) OR (((doi_tuong)::text = 'NGUOI_DUNG'::text) AND (loai_tai_khoan IS NULL) AND (goi_dich_vu_id IS NULL)) OR (((doi_tuong)::text = 'LOAI_TAI_KHOAN'::text) AND (loai_tai_khoan IS NOT NULL) AND (goi_dich_vu_id IS NULL)) OR (((doi_tuong)::text = 'GOI_DICH_VU'::text) AND (loai_tai_khoan IS NULL) AND (goi_dich_vu_id IS NOT NULL)))),
    CONSTRAINT chk_chinh_sach_han_muc_don_vi CHECK (((don_vi)::text = ANY ((ARRAY['LAN'::character varying, 'TEP'::character varying, 'BYTE'::character varying])::text[]))),
    CONSTRAINT chk_chinh_sach_han_muc_gioi_han CHECK ((((khong_gioi_han = true) AND (gioi_han IS NULL)) OR ((khong_gioi_han = false) AND (gioi_han IS NOT NULL) AND (gioi_han >= 0)))),
    CONSTRAINT chk_chinh_sach_han_muc_hieu_luc CHECK (((hieu_luc_den IS NULL) OR (hieu_luc_tu < hieu_luc_den))),
    CONSTRAINT chk_chinh_sach_han_muc_khi_vuot CHECK (((hanh_dong_khi_vuot)::text = ANY ((ARRAY['TU_CHOI'::character varying, 'YEU_CAU_DANG_NHAP'::character varying, 'YEU_CAU_NANG_CAP'::character varying])::text[]))),
    CONSTRAINT chk_chinh_sach_han_muc_loai_tai_khoan CHECK (((loai_tai_khoan IS NULL) OR (btrim((loai_tai_khoan)::text) <> ''::text))),
    CONSTRAINT chk_chinh_sach_han_muc_ma CHECK ((btrim((ma)::text) <> ''::text)),
    CONSTRAINT chk_chinh_sach_han_muc_ma_hanh_dong CHECK ((btrim((ma_hanh_dong)::text) <> ''::text)),
    CONSTRAINT chk_chinh_sach_han_muc_ten CHECK ((btrim((ten)::text) <> ''::text)),
    CONSTRAINT chk_chinh_sach_han_muc_upload CHECK ((((ma_hanh_dong)::text <> ALL ((ARRAY['UPLOAD_TONG_SO_LAN'::character varying, 'UPLOAD_TONG_SO_TEP'::character varying, 'UPLOAD_SO_TEP_MOI_LAN'::character varying, 'UPLOAD_KICH_THUOC_MOI_TEP'::character varying])::text[])) OR (((ma_hanh_dong)::text = 'UPLOAD_TONG_SO_LAN'::text) AND ((don_vi)::text = 'LAN'::text) AND ((chu_ky)::text = 'NGAY'::text)) OR (((ma_hanh_dong)::text = 'UPLOAD_TONG_SO_TEP'::text) AND ((don_vi)::text = 'TEP'::text) AND ((chu_ky)::text = 'THEO_GOI'::text) AND ((khong_gioi_han = true) OR ((doi_tuong)::text = 'GOI_DICH_VU'::text))) OR (((ma_hanh_dong)::text = 'UPLOAD_SO_TEP_MOI_LAN'::text) AND ((don_vi)::text = 'TEP'::text) AND ((chu_ky)::text = 'MOI_REQUEST'::text)) OR (((ma_hanh_dong)::text = 'UPLOAD_KICH_THUOC_MOI_TEP'::text) AND ((don_vi)::text = 'BYTE'::text) AND ((chu_ky)::text = 'MOI_TEP'::text)))),
    CONSTRAINT chk_chinh_sach_han_muc_upload_khong_gioi_han CHECK ((((ma_hanh_dong)::text <> ALL ((ARRAY['UPLOAD_SO_TEP_MOI_LAN'::character varying, 'UPLOAD_KICH_THUOC_MOI_TEP'::character varying])::text[])) OR (khong_gioi_han = false))),
    CONSTRAINT chk_chinh_sach_han_muc_uu_tien CHECK ((muc_do_uu_tien >= 1))
);


--
-- Name: chinh_sach_han_muc_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chinh_sach_han_muc ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chinh_sach_han_muc_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chuyen_doi; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chuyen_doi (
    id integer NOT NULL,
    cong_viec_id integer NOT NULL,
    buoc_cong_viec_id integer,
    thu_tu integer DEFAULT 1 NOT NULL,
    lan_thu integer DEFAULT 1 NOT NULL,
    phien_ban_nguon_id integer,
    phien_ban_ket_qua_id integer,
    dinh_dang_nguon character varying(50) NOT NULL,
    dinh_dang_dich character varying(50) NOT NULL,
    converter_key character varying(255) NOT NULL,
    engine character varying(100),
    phien_ban_engine character varying(100),
    trang_thai character varying(30) DEFAULT 'CHO_XU_LY'::character varying NOT NULL,
    tuy_chon jsonb DEFAULT '{}'::jsonb NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    thong_ke jsonb DEFAULT '{}'::jsonb NOT NULL,
    ma_loi character varying(100),
    thong_bao_loi text,
    chi_tiet_loi jsonb,
    bat_dau_luc timestamp with time zone,
    hoan_thanh_luc timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_chuyen_doi_lan_thu CHECK ((lan_thu > 0)),
    CONSTRAINT chk_chuyen_doi_thu_tu CHECK ((thu_tu > 0)),
    CONSTRAINT chk_chuyen_doi_trang_thai CHECK (((trang_thai)::text = ANY ((ARRAY['CHO_XU_LY'::character varying, 'DANG_XU_LY'::character varying, 'HOAN_THANH'::character varying, 'THAT_BAI'::character varying, 'DA_HUY'::character varying])::text[])))
);


--
-- Name: chuyen_doi_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chuyen_doi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chuyen_doi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cong_viec; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cong_viec (
    id integer NOT NULL,
    nguoi_dung_id integer,
    phien_khach_id integer,
    request_id uuid DEFAULT gen_random_uuid() NOT NULL,
    khoa_idempotency character varying(128),
    loai_cong_viec character varying(50) NOT NULL,
    trang_thai character varying(30) DEFAULT 'CHO_XU_LY'::character varying NOT NULL,
    muc_do_uu_tien smallint DEFAULT 5 NOT NULL,
    tien_trinh numeric(5,2) DEFAULT 0 NOT NULL,
    buoc_hien_tai character varying(255),
    tep_nguon_id integer,
    phien_ban_nguon_id integer,
    tep_ket_qua_id integer,
    phien_ban_ket_qua_id integer,
    dinh_dang_nguon character varying(50),
    dinh_dang_dich character varying(50),
    dau_vao jsonb DEFAULT '{}'::jsonb NOT NULL,
    tuy_chon jsonb DEFAULT '{}'::jsonb NOT NULL,
    dau_ra jsonb DEFAULT '{}'::jsonb NOT NULL,
    queue_name character varying(100),
    queue_job_id character varying(255),
    so_lan_thu integer DEFAULT 0 NOT NULL,
    so_lan_thu_toi_da integer DEFAULT 3 NOT NULL,
    ma_loi character varying(100),
    thong_bao_loi text,
    chi_tiet_loi jsonb,
    xep_hang_luc timestamp with time zone,
    bat_dau_luc timestamp with time zone,
    hoan_thanh_luc timestamp with time zone,
    huy_luc timestamp with time zone,
    het_han_luc timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_cong_viec_chu_so_huu CHECK ((NOT ((nguoi_dung_id IS NOT NULL) AND (phien_khach_id IS NOT NULL)))),
    CONSTRAINT chk_cong_viec_so_lan_thu CHECK (((so_lan_thu >= 0) AND (so_lan_thu_toi_da >= 0))),
    CONSTRAINT chk_cong_viec_tien_trinh CHECK (((tien_trinh >= (0)::numeric) AND (tien_trinh <= (100)::numeric))),
    CONSTRAINT chk_cong_viec_trang_thai CHECK (((trang_thai)::text = ANY ((ARRAY['CHO_XU_LY'::character varying, 'DANG_PHAN_TICH'::character varying, 'DANG_XU_LY'::character varying, 'DANG_CHUYEN_DOI'::character varying, 'DANG_KET_XUAT'::character varying, 'DANG_OCR'::character varying, 'DANG_DICH'::character varying, 'HOAN_THANH'::character varying, 'THAT_BAI'::character varying, 'DANG_HUY'::character varying, 'DA_HUY'::character varying])::text[]))),
    CONSTRAINT chk_cong_viec_uu_tien CHECK (((muc_do_uu_tien >= 1) AND (muc_do_uu_tien <= 10)))
);


--
-- Name: cong_viec_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cong_viec ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cong_viec_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dang_ky_goi; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dang_ky_goi (
    id integer NOT NULL,
    nguoi_dung_id integer NOT NULL,
    goi_dich_vu_id integer NOT NULL,
    trang_thai character varying(30) DEFAULT 'CHO_THANH_TOAN'::character varying NOT NULL,
    nguon_kich_hoat character varying(30) DEFAULT 'THANH_TOAN'::character varying NOT NULL,
    gia_thanh_toan numeric(18,2) DEFAULT 0 NOT NULL,
    tien_te character varying(3) DEFAULT 'VND'::character varying NOT NULL,
    ma_giao_dich character varying(255),
    bat_dau_luc timestamp with time zone,
    het_han_luc timestamp with time zone,
    huy_luc timestamp with time zone,
    tu_dong_gia_han boolean DEFAULT false NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_dang_ky_goi_gia CHECK ((gia_thanh_toan >= (0)::numeric)),
    CONSTRAINT chk_dang_ky_goi_nguon CHECK (((nguon_kich_hoat)::text = ANY ((ARRAY['THANH_TOAN'::character varying, 'QUAN_TRI'::character varying, 'KHUYEN_MAI'::character varying, 'HE_THONG'::character varying])::text[]))),
    CONSTRAINT chk_dang_ky_goi_thoi_gian CHECK (((het_han_luc IS NULL) OR (bat_dau_luc IS NULL) OR (bat_dau_luc < het_han_luc))),
    CONSTRAINT chk_dang_ky_goi_tien_te CHECK (((tien_te)::text ~ '^[A-Z]{3}$'::text)),
    CONSTRAINT chk_dang_ky_goi_trang_thai CHECK (((trang_thai)::text = ANY ((ARRAY['CHO_THANH_TOAN'::character varying, 'HOAT_DONG'::character varying, 'TAM_DUNG'::character varying, 'HET_HAN'::character varying, 'DA_HUY'::character varying])::text[])))
);


--
-- Name: dang_ky_goi_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dang_ky_goi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dang_ky_goi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: goi_dich_vu; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goi_dich_vu (
    id integer NOT NULL,
    ma character varying(50) NOT NULL,
    ten character varying(255) NOT NULL,
    mo_ta text,
    gia numeric(18,2) DEFAULT 0 NOT NULL,
    tien_te character varying(3) DEFAULT 'VND'::character varying NOT NULL,
    yeu_cau_thanh_toan boolean DEFAULT true NOT NULL,
    chu_ky character varying(30) DEFAULT 'THANG'::character varying NOT NULL,
    so_chu_ky integer DEFAULT 1 NOT NULL,
    thu_tu integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    xoa_luc timestamp with time zone,
    CONSTRAINT chk_goi_dich_vu_chu_ky CHECK (((chu_ky)::text = ANY ((ARRAY['THANG'::character varying, 'NAM'::character varying, 'MOT_LAN'::character varying])::text[]))),
    CONSTRAINT chk_goi_dich_vu_gia CHECK ((gia >= (0)::numeric)),
    CONSTRAINT chk_goi_dich_vu_mien_phi CHECK (((yeu_cau_thanh_toan = true) OR (gia = (0)::numeric))),
    CONSTRAINT chk_goi_dich_vu_so_chu_ky CHECK ((so_chu_ky > 0)),
    CONSTRAINT chk_goi_dich_vu_tien_te CHECK (((tien_te)::text ~ '^[A-Z]{3}$'::text))
);


--
-- Name: goi_dich_vu_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.goi_dich_vu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goi_dich_vu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lich_su; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lich_su (
    id integer NOT NULL,
    nguoi_dung_id integer,
    phien_khach_id integer,
    cong_viec_id integer,
    tep_id integer,
    phien_ban_tep_id integer,
    loai_su_kien character varying(100) NOT NULL,
    nguon character varying(50) DEFAULT 'HE_THONG'::character varying NOT NULL,
    tieu_de character varying(255) NOT NULL,
    mo_ta text,
    du_lieu jsonb DEFAULT '{}'::jsonb NOT NULL,
    hien_thi_cho_nguoi_dung boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_lich_su_chu_so_huu CHECK ((NOT ((nguoi_dung_id IS NOT NULL) AND (phien_khach_id IS NOT NULL))))
);


--
-- Name: lich_su_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lich_su ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lich_su_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ma_xac_thuc; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ma_xac_thuc (
    id integer NOT NULL,
    nguoi_dung_id integer,
    kenh character varying(20) DEFAULT 'EMAIL'::character varying NOT NULL,
    dia_chi character varying(320) NOT NULL,
    muc_dich character varying(50) NOT NULL,
    ma_hash character(64) NOT NULL,
    trang_thai character varying(30) DEFAULT 'CHO_XAC_THUC'::character varying NOT NULL,
    so_lan_thu integer DEFAULT 0 NOT NULL,
    so_lan_thu_toi_da integer DEFAULT 5 NOT NULL,
    so_lan_gui integer DEFAULT 1 NOT NULL,
    gui_lan_cuoi_luc timestamp with time zone DEFAULT now() NOT NULL,
    het_han_luc timestamp with time zone NOT NULL,
    xac_thuc_luc timestamp with time zone,
    vo_hieu_hoa_luc timestamp with time zone,
    request_id uuid DEFAULT gen_random_uuid() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_ma_xac_thuc_kenh CHECK (((kenh)::text = ANY ((ARRAY['EMAIL'::character varying, 'SMS'::character varying])::text[]))),
    CONSTRAINT chk_ma_xac_thuc_so_lan CHECK (((so_lan_thu >= 0) AND (so_lan_thu_toi_da > 0) AND (so_lan_gui > 0))),
    CONSTRAINT chk_ma_xac_thuc_trang_thai CHECK (((trang_thai)::text = ANY ((ARRAY['CHO_XAC_THUC'::character varying, 'DA_XAC_THUC'::character varying, 'HET_HAN'::character varying, 'VO_HIEU_HOA'::character varying, 'VUOT_SO_LAN_THU'::character varying])::text[])))
);


--
-- Name: ma_xac_thuc_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ma_xac_thuc ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ma_xac_thuc_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nguoi_dung; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nguoi_dung (
    id integer NOT NULL,
    email character varying(320) NOT NULL,
    ten_dang_nhap character varying(100),
    ho_ten character varying(255) NOT NULL,
    mat_khau_hash character varying(255),
    loai_tai_khoan character varying(30) DEFAULT 'NGUOI_DUNG'::character varying NOT NULL,
    trang_thai character varying(30) DEFAULT 'HOAT_DONG'::character varying NOT NULL,
    email_xac_thuc_luc timestamp with time zone,
    lan_dang_nhap_cuoi_luc timestamp with time zone,
    cai_dat jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    xoa_luc timestamp with time zone,
    CONSTRAINT chk_nguoi_dung_loai_tai_khoan CHECK (((loai_tai_khoan)::text = ANY ((ARRAY['NGUOI_DUNG'::character varying, 'QUAN_TRI'::character varying, 'HE_THONG'::character varying])::text[]))),
    CONSTRAINT chk_nguoi_dung_trang_thai CHECK (((trang_thai)::text = ANY ((ARRAY['HOAT_DONG'::character varying, 'TAM_KHOA'::character varying, 'VO_HIEU_HOA'::character varying])::text[])))
);


--
-- Name: nguoi_dung_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.nguoi_dung ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nguoi_dung_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nhat_ky; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nhat_ky (
    id bigint NOT NULL,
    muc_do character varying(20) DEFAULT 'INFO'::character varying NOT NULL,
    nguon character varying(100) NOT NULL,
    ma_su_kien character varying(100),
    request_id uuid,
    trace_id character varying(100),
    nguoi_dung_id integer,
    phien_khach_id integer,
    cong_viec_id integer,
    buoc_cong_viec_id integer,
    tep_id integer,
    phuong_thuc_http character varying(10),
    duong_dan_http text,
    http_status integer,
    dia_chi_ip inet,
    user_agent text,
    thong_diep text NOT NULL,
    du_lieu jsonb DEFAULT '{}'::jsonb NOT NULL,
    stack_trace text,
    het_han_luc timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_nhat_ky_http_status CHECK (((http_status IS NULL) OR ((http_status >= 100) AND (http_status <= 599)))),
    CONSTRAINT chk_nhat_ky_muc_do CHECK (((muc_do)::text = ANY ((ARRAY['DEBUG'::character varying, 'INFO'::character varying, 'WARN'::character varying, 'ERROR'::character varying, 'SECURITY'::character varying, 'AUDIT'::character varying])::text[])))
);


--
-- Name: nhat_ky_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.nhat_ky ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nhat_ky_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: phien_ban_tep; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.phien_ban_tep (
    id integer NOT NULL,
    tep_id integer NOT NULL,
    phien_ban_cha_id integer,
    cong_viec_tao_id integer,
    so_phien_ban integer NOT NULL,
    loai_phien_ban character varying(30) DEFAULT 'GOC'::character varying NOT NULL,
    ten_tep character varying(255) NOT NULL,
    phan_mo_rong character varying(32),
    dinh_dang character varying(50),
    mime_type character varying(255),
    kich_thuoc_bytes bigint DEFAULT 0 NOT NULL,
    hash_sha256 character varying(64),
    storage_driver character varying(30) NOT NULL,
    storage_bucket character varying(255),
    storage_key text NOT NULL,
    storage_etag character varying(255),
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    trang_thai character varying(30) DEFAULT 'DANG_TAO'::character varying NOT NULL,
    het_han_luc timestamp with time zone,
    xoa_luc timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_phien_ban_tep_hash CHECK (((hash_sha256 IS NULL) OR ((hash_sha256)::text ~ '^[0-9a-f]{64}$'::text))),
    CONSTRAINT chk_phien_ban_tep_kich_thuoc CHECK ((kich_thuoc_bytes >= 0)),
    CONSTRAINT chk_phien_ban_tep_loai CHECK (((loai_phien_ban)::text = ANY ((ARRAY['GOC'::character varying, 'LAM_VIEC'::character varying, 'KET_QUA'::character varying, 'TRUNG_GIAN'::character varying, 'XEM_TRUOC'::character varying])::text[]))),
    CONSTRAINT chk_phien_ban_tep_so_phien_ban CHECK ((so_phien_ban > 0)),
    CONSTRAINT chk_phien_ban_tep_trang_thai CHECK (((trang_thai)::text = ANY ((ARRAY['DANG_TAO'::character varying, 'SAN_SANG'::character varying, 'LOI'::character varying, 'DA_XOA'::character varying])::text[])))
);


--
-- Name: phien_ban_tep_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.phien_ban_tep ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.phien_ban_tep_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: phien_dang_nhap; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.phien_dang_nhap (
    id integer NOT NULL,
    nguoi_dung_id integer NOT NULL,
    jti uuid NOT NULL,
    refresh_token_hash character(64) NOT NULL,
    dia_chi_ip inet,
    user_agent character varying(1000),
    het_han_luc timestamp with time zone NOT NULL,
    su_dung_lan_cuoi_luc timestamp with time zone,
    vo_hieu_hoa_luc timestamp with time zone,
    ly_do_vo_hieu_hoa character varying(255),
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_phien_dang_nhap_het_han CHECK ((het_han_luc > created_at))
);


--
-- Name: phien_dang_nhap_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.phien_dang_nhap ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.phien_dang_nhap_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: phien_khach; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.phien_khach (
    id integer NOT NULL,
    token_hash character(64) NOT NULL,
    trang_thai character varying(30) DEFAULT 'HOAT_DONG'::character varying NOT NULL,
    dia_chi_ip_dau inet,
    dia_chi_ip_cuoi inet,
    user_agent_hash character(64),
    lan_su_dung_cuoi_luc timestamp with time zone DEFAULT now() NOT NULL,
    het_han_luc timestamp with time zone,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_phien_khach_trang_thai CHECK (((trang_thai)::text = ANY ((ARRAY['HOAT_DONG'::character varying, 'VO_HIEU_HOA'::character varying])::text[])))
);


--
-- Name: phien_khach_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.phien_khach ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.phien_khach_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: su_dung_han_muc; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.su_dung_han_muc (
    id bigint NOT NULL,
    nguoi_dung_id integer,
    phien_khach_id integer,
    chinh_sach_han_muc_id integer,
    ma_hanh_dong character varying(50) NOT NULL,
    don_vi character varying(20) NOT NULL,
    ky_bat_dau timestamp with time zone NOT NULL,
    ky_ket_thuc timestamp with time zone NOT NULL,
    da_su_dung bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_su_dung_han_muc_chu_the CHECK ((((nguoi_dung_id IS NOT NULL) AND (phien_khach_id IS NULL)) OR ((nguoi_dung_id IS NULL) AND (phien_khach_id IS NOT NULL)))),
    CONSTRAINT chk_su_dung_han_muc_don_vi CHECK (((don_vi)::text = ANY ((ARRAY['LAN'::character varying, 'TEP'::character varying, 'BYTE'::character varying])::text[]))),
    CONSTRAINT chk_su_dung_han_muc_ky CHECK ((ky_bat_dau < ky_ket_thuc)),
    CONSTRAINT chk_su_dung_han_muc_so_luong CHECK ((da_su_dung >= 0))
);


--
-- Name: su_dung_han_muc_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.su_dung_han_muc ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.su_dung_han_muc_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tep; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tep (
    id integer NOT NULL,
    nguoi_dung_id integer,
    phien_khach_id integer,
    ten_tep character varying(255) CONSTRAINT tep_ho_ten_not_null NOT NULL,
    mo_ta text,
    nguon_tao character varying(30) DEFAULT 'UPLOAD'::character varying NOT NULL,
    trang_thai character varying(30) DEFAULT 'HOAT_DONG'::character varying NOT NULL,
    thuoc_tinh jsonb DEFAULT '{}'::jsonb NOT NULL,
    het_han_luc timestamp with time zone,
    xoa_luc timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_tep_chu_so_huu CHECK ((NOT ((nguoi_dung_id IS NOT NULL) AND (phien_khach_id IS NOT NULL)))),
    CONSTRAINT chk_tep_nguon_tao CHECK (((nguon_tao)::text = ANY ((ARRAY['UPLOAD'::character varying, 'CONG_VIEC'::character varying, 'HE_THONG'::character varying])::text[]))),
    CONSTRAINT chk_tep_trang_thai CHECK (((trang_thai)::text = ANY ((ARRAY['HOAT_DONG'::character varying, 'HET_HAN'::character varying, 'DA_XOA'::character varying])::text[])))
);


--
-- Name: tep_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tep ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tep_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: buoc_cong_viec buoc_cong_viec_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buoc_cong_viec
    ADD CONSTRAINT buoc_cong_viec_pkey PRIMARY KEY (id);


--
-- Name: chinh_sach_han_muc chinh_sach_han_muc_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chinh_sach_han_muc
    ADD CONSTRAINT chinh_sach_han_muc_pkey PRIMARY KEY (id);


--
-- Name: chuyen_doi chuyen_doi_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chuyen_doi
    ADD CONSTRAINT chuyen_doi_pkey PRIMARY KEY (id);


--
-- Name: cong_viec cong_viec_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cong_viec
    ADD CONSTRAINT cong_viec_pkey PRIMARY KEY (id);


--
-- Name: dang_ky_goi dang_ky_goi_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dang_ky_goi
    ADD CONSTRAINT dang_ky_goi_pkey PRIMARY KEY (id);


--
-- Name: goi_dich_vu goi_dich_vu_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goi_dich_vu
    ADD CONSTRAINT goi_dich_vu_pkey PRIMARY KEY (id);


--
-- Name: lich_su lich_su_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lich_su
    ADD CONSTRAINT lich_su_pkey PRIMARY KEY (id);


--
-- Name: ma_xac_thuc ma_xac_thuc_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ma_xac_thuc
    ADD CONSTRAINT ma_xac_thuc_pkey PRIMARY KEY (id);


--
-- Name: nguoi_dung nguoi_dung_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nguoi_dung
    ADD CONSTRAINT nguoi_dung_pkey PRIMARY KEY (id);


--
-- Name: nhat_ky nhat_ky_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nhat_ky
    ADD CONSTRAINT nhat_ky_pkey PRIMARY KEY (id);


--
-- Name: phien_ban_tep phien_ban_tep_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phien_ban_tep
    ADD CONSTRAINT phien_ban_tep_pkey PRIMARY KEY (id);


--
-- Name: phien_dang_nhap phien_dang_nhap_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phien_dang_nhap
    ADD CONSTRAINT phien_dang_nhap_pkey PRIMARY KEY (id);


--
-- Name: phien_khach phien_khach_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phien_khach
    ADD CONSTRAINT phien_khach_pkey PRIMARY KEY (id);


--
-- Name: su_dung_han_muc su_dung_han_muc_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.su_dung_han_muc
    ADD CONSTRAINT su_dung_han_muc_pkey PRIMARY KEY (id);


--
-- Name: tep tep_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tep
    ADD CONSTRAINT tep_pkey PRIMARY KEY (id);


--
-- Name: buoc_cong_viec uq_buoc_cong_viec_thu_tu; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buoc_cong_viec
    ADD CONSTRAINT uq_buoc_cong_viec_thu_tu UNIQUE (cong_viec_id, thu_tu);


--
-- Name: chuyen_doi uq_chuyen_doi_lan_thu; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chuyen_doi
    ADD CONSTRAINT uq_chuyen_doi_lan_thu UNIQUE (cong_viec_id, thu_tu, lan_thu);


--
-- Name: cong_viec uq_cong_viec_request_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cong_viec
    ADD CONSTRAINT uq_cong_viec_request_id UNIQUE (request_id);


--
-- Name: phien_ban_tep uq_phien_ban_tep_so; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phien_ban_tep
    ADD CONSTRAINT uq_phien_ban_tep_so UNIQUE (tep_id, so_phien_ban);


--
-- Name: phien_dang_nhap uq_phien_dang_nhap_jti; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phien_dang_nhap
    ADD CONSTRAINT uq_phien_dang_nhap_jti UNIQUE (jti);


--
-- Name: phien_dang_nhap uq_phien_dang_nhap_refresh_token_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phien_dang_nhap
    ADD CONSTRAINT uq_phien_dang_nhap_refresh_token_hash UNIQUE (refresh_token_hash);


--
-- Name: idx_buoc_cong_viec_cong_viec; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_buoc_cong_viec_cong_viec ON public.buoc_cong_viec USING btree (cong_viec_id, thu_tu);


--
-- Name: idx_buoc_cong_viec_queue; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_buoc_cong_viec_queue ON public.buoc_cong_viec USING btree (queue_name, queue_job_id) WHERE (queue_job_id IS NOT NULL);


--
-- Name: idx_buoc_cong_viec_trang_thai; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_buoc_cong_viec_trang_thai ON public.buoc_cong_viec USING btree (trang_thai);


--
-- Name: idx_chinh_sach_han_muc_goi; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chinh_sach_han_muc_goi ON public.chinh_sach_han_muc USING btree (goi_dich_vu_id, ma_hanh_dong, active, muc_do_uu_tien) WHERE (goi_dich_vu_id IS NOT NULL);


--
-- Name: idx_chinh_sach_han_muc_hieu_luc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chinh_sach_han_muc_hieu_luc ON public.chinh_sach_han_muc USING btree (hieu_luc_tu, hieu_luc_den) WHERE (active = true);


--
-- Name: idx_chinh_sach_han_muc_loai_tai_khoan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chinh_sach_han_muc_loai_tai_khoan ON public.chinh_sach_han_muc USING btree (loai_tai_khoan, ma_hanh_dong, active, muc_do_uu_tien) WHERE (loai_tai_khoan IS NOT NULL);


--
-- Name: idx_chinh_sach_han_muc_tim_kiem; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chinh_sach_han_muc_tim_kiem ON public.chinh_sach_han_muc USING btree (doi_tuong, ma_hanh_dong, active, muc_do_uu_tien);


--
-- Name: idx_chuyen_doi_buoc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chuyen_doi_buoc ON public.chuyen_doi USING btree (buoc_cong_viec_id) WHERE (buoc_cong_viec_id IS NOT NULL);


--
-- Name: idx_chuyen_doi_cong_viec; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chuyen_doi_cong_viec ON public.chuyen_doi USING btree (cong_viec_id, thu_tu, lan_thu);


--
-- Name: idx_chuyen_doi_converter; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chuyen_doi_converter ON public.chuyen_doi USING btree (converter_key, created_at DESC);


--
-- Name: idx_chuyen_doi_phien_ban_ket_qua; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chuyen_doi_phien_ban_ket_qua ON public.chuyen_doi USING btree (phien_ban_ket_qua_id) WHERE (phien_ban_ket_qua_id IS NOT NULL);


--
-- Name: idx_chuyen_doi_phien_ban_nguon; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chuyen_doi_phien_ban_nguon ON public.chuyen_doi USING btree (phien_ban_nguon_id) WHERE (phien_ban_nguon_id IS NOT NULL);


--
-- Name: idx_chuyen_doi_trang_thai; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chuyen_doi_trang_thai ON public.chuyen_doi USING btree (trang_thai, created_at DESC);


--
-- Name: idx_cong_viec_het_han; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cong_viec_het_han ON public.cong_viec USING btree (het_han_luc) WHERE (het_han_luc IS NOT NULL);


--
-- Name: idx_cong_viec_nguoi_dung; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cong_viec_nguoi_dung ON public.cong_viec USING btree (nguoi_dung_id, created_at DESC) WHERE (nguoi_dung_id IS NOT NULL);


--
-- Name: idx_cong_viec_phien_khach; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cong_viec_phien_khach ON public.cong_viec USING btree (phien_khach_id, created_at DESC) WHERE (phien_khach_id IS NOT NULL);


--
-- Name: idx_cong_viec_queue; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cong_viec_queue ON public.cong_viec USING btree (queue_name, queue_job_id) WHERE (queue_job_id IS NOT NULL);


--
-- Name: idx_cong_viec_tep_ket_qua; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cong_viec_tep_ket_qua ON public.cong_viec USING btree (tep_ket_qua_id) WHERE (tep_ket_qua_id IS NOT NULL);


--
-- Name: idx_cong_viec_tep_nguon; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cong_viec_tep_nguon ON public.cong_viec USING btree (tep_nguon_id) WHERE (tep_nguon_id IS NOT NULL);


--
-- Name: idx_cong_viec_trang_thai; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cong_viec_trang_thai ON public.cong_viec USING btree (trang_thai, muc_do_uu_tien DESC, created_at);


--
-- Name: idx_dang_ky_goi_goi; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dang_ky_goi_goi ON public.dang_ky_goi USING btree (goi_dich_vu_id, trang_thai);


--
-- Name: idx_dang_ky_goi_het_han; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dang_ky_goi_het_han ON public.dang_ky_goi USING btree (het_han_luc) WHERE (((trang_thai)::text = 'HOAT_DONG'::text) AND (het_han_luc IS NOT NULL));


--
-- Name: idx_dang_ky_goi_nguoi_dung; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dang_ky_goi_nguoi_dung ON public.dang_ky_goi USING btree (nguoi_dung_id, created_at DESC);


--
-- Name: idx_goi_dich_vu_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_goi_dich_vu_active ON public.goi_dich_vu USING btree (active, thu_tu, created_at) WHERE (xoa_luc IS NULL);


--
-- Name: idx_lich_su_cong_viec; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lich_su_cong_viec ON public.lich_su USING btree (cong_viec_id, created_at DESC) WHERE (cong_viec_id IS NOT NULL);


--
-- Name: idx_lich_su_hien_thi; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lich_su_hien_thi ON public.lich_su USING btree (created_at DESC) WHERE (hien_thi_cho_nguoi_dung = true);


--
-- Name: idx_lich_su_loai_su_kien; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lich_su_loai_su_kien ON public.lich_su USING btree (loai_su_kien, created_at DESC);


--
-- Name: idx_lich_su_nguoi_dung; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lich_su_nguoi_dung ON public.lich_su USING btree (nguoi_dung_id, created_at DESC) WHERE (nguoi_dung_id IS NOT NULL);


--
-- Name: idx_lich_su_phien_khach; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lich_su_phien_khach ON public.lich_su USING btree (phien_khach_id, created_at DESC) WHERE (phien_khach_id IS NOT NULL);


--
-- Name: idx_lich_su_tep; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_lich_su_tep ON public.lich_su USING btree (tep_id, created_at DESC) WHERE (tep_id IS NOT NULL);


--
-- Name: idx_ma_xac_thuc_cho_xac_thuc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ma_xac_thuc_cho_xac_thuc ON public.ma_xac_thuc USING btree (lower((dia_chi)::text), muc_dich, het_han_luc) WHERE ((trang_thai)::text = 'CHO_XAC_THUC'::text);


--
-- Name: idx_ma_xac_thuc_dia_chi; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ma_xac_thuc_dia_chi ON public.ma_xac_thuc USING btree (lower((dia_chi)::text), muc_dich, created_at DESC);


--
-- Name: idx_ma_xac_thuc_nguoi_dung; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ma_xac_thuc_nguoi_dung ON public.ma_xac_thuc USING btree (nguoi_dung_id, created_at DESC) WHERE (nguoi_dung_id IS NOT NULL);


--
-- Name: idx_nguoi_dung_trang_thai; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nguoi_dung_trang_thai ON public.nguoi_dung USING btree (trang_thai) WHERE (xoa_luc IS NULL);


--
-- Name: idx_nhat_ky_cong_viec; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nhat_ky_cong_viec ON public.nhat_ky USING btree (cong_viec_id, created_at DESC) WHERE (cong_viec_id IS NOT NULL);


--
-- Name: idx_nhat_ky_created_brin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nhat_ky_created_brin ON public.nhat_ky USING brin (created_at);


--
-- Name: idx_nhat_ky_het_han; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nhat_ky_het_han ON public.nhat_ky USING btree (het_han_luc) WHERE (het_han_luc IS NOT NULL);


--
-- Name: idx_nhat_ky_ma_su_kien; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nhat_ky_ma_su_kien ON public.nhat_ky USING btree (ma_su_kien, created_at DESC) WHERE (ma_su_kien IS NOT NULL);


--
-- Name: idx_nhat_ky_muc_do; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nhat_ky_muc_do ON public.nhat_ky USING btree (muc_do, created_at DESC);


--
-- Name: idx_nhat_ky_nguoi_dung; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nhat_ky_nguoi_dung ON public.nhat_ky USING btree (nguoi_dung_id, created_at DESC) WHERE (nguoi_dung_id IS NOT NULL);


--
-- Name: idx_nhat_ky_request; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nhat_ky_request ON public.nhat_ky USING btree (request_id) WHERE (request_id IS NOT NULL);


--
-- Name: idx_nhat_ky_trace; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nhat_ky_trace ON public.nhat_ky USING btree (trace_id) WHERE (trace_id IS NOT NULL);


--
-- Name: idx_phien_ban_tep_cha; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_phien_ban_tep_cha ON public.phien_ban_tep USING btree (phien_ban_cha_id) WHERE (phien_ban_cha_id IS NOT NULL);


--
-- Name: idx_phien_ban_tep_cong_viec_tao; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_phien_ban_tep_cong_viec_tao ON public.phien_ban_tep USING btree (cong_viec_tao_id) WHERE (cong_viec_tao_id IS NOT NULL);


--
-- Name: idx_phien_ban_tep_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_phien_ban_tep_hash ON public.phien_ban_tep USING btree (hash_sha256) WHERE (hash_sha256 IS NOT NULL);


--
-- Name: idx_phien_ban_tep_het_han; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_phien_ban_tep_het_han ON public.phien_ban_tep USING btree (het_han_luc) WHERE ((het_han_luc IS NOT NULL) AND (xoa_luc IS NULL));


--
-- Name: idx_phien_ban_tep_tep; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_phien_ban_tep_tep ON public.phien_ban_tep USING btree (tep_id, so_phien_ban DESC);


--
-- Name: idx_phien_dang_nhap_het_han; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_phien_dang_nhap_het_han ON public.phien_dang_nhap USING btree (het_han_luc);


--
-- Name: idx_phien_dang_nhap_nguoi_dung; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_phien_dang_nhap_nguoi_dung ON public.phien_dang_nhap USING btree (nguoi_dung_id);


--
-- Name: idx_phien_dang_nhap_nguoi_dung_hoat_dong; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_phien_dang_nhap_nguoi_dung_hoat_dong ON public.phien_dang_nhap USING btree (nguoi_dung_id, het_han_luc) WHERE (vo_hieu_hoa_luc IS NULL);


--
-- Name: idx_phien_khach_het_han; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_phien_khach_het_han ON public.phien_khach USING btree (het_han_luc) WHERE (het_han_luc IS NOT NULL);


--
-- Name: idx_phien_khach_hoat_dong; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_phien_khach_hoat_dong ON public.phien_khach USING btree (lan_su_dung_cuoi_luc DESC) WHERE ((trang_thai)::text = 'HOAT_DONG'::text);


--
-- Name: idx_su_dung_han_muc_hanh_dong; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_su_dung_han_muc_hanh_dong ON public.su_dung_han_muc USING btree (ma_hanh_dong, ky_bat_dau, ky_ket_thuc);


--
-- Name: idx_su_dung_han_muc_ky; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_su_dung_han_muc_ky ON public.su_dung_han_muc USING btree (ky_ket_thuc);


--
-- Name: idx_tep_het_han; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tep_het_han ON public.tep USING btree (het_han_luc) WHERE ((het_han_luc IS NOT NULL) AND (xoa_luc IS NULL));


--
-- Name: idx_tep_nguoi_dung; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tep_nguoi_dung ON public.tep USING btree (nguoi_dung_id, created_at DESC) WHERE (xoa_luc IS NULL);


--
-- Name: idx_tep_phien_khach; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tep_phien_khach ON public.tep USING btree (phien_khach_id, created_at DESC) WHERE ((phien_khach_id IS NOT NULL) AND (xoa_luc IS NULL));


--
-- Name: idx_tep_trang_thai; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tep_trang_thai ON public.tep USING btree (trang_thai, created_at DESC);


--
-- Name: uq_chinh_sach_han_muc_ma; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_chinh_sach_han_muc_ma ON public.chinh_sach_han_muc USING btree (lower((ma)::text));


--
-- Name: uq_cong_viec_idempotency_khach; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_cong_viec_idempotency_khach ON public.cong_viec USING btree (phien_khach_id, khoa_idempotency) WHERE ((phien_khach_id IS NOT NULL) AND (khoa_idempotency IS NOT NULL));


--
-- Name: uq_cong_viec_idempotency_nguoi_dung; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_cong_viec_idempotency_nguoi_dung ON public.cong_viec USING btree (nguoi_dung_id, khoa_idempotency) WHERE ((nguoi_dung_id IS NOT NULL) AND (khoa_idempotency IS NOT NULL));


--
-- Name: uq_dang_ky_goi_dang_hoat_dong; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_dang_ky_goi_dang_hoat_dong ON public.dang_ky_goi USING btree (nguoi_dung_id) WHERE ((trang_thai)::text = 'HOAT_DONG'::text);


--
-- Name: uq_goi_dich_vu_ma; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_goi_dich_vu_ma ON public.goi_dich_vu USING btree (lower((ma)::text)) WHERE (xoa_luc IS NULL);


--
-- Name: uq_ma_xac_thuc_request; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_ma_xac_thuc_request ON public.ma_xac_thuc USING btree (request_id);


--
-- Name: uq_nguoi_dung_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_nguoi_dung_email ON public.nguoi_dung USING btree (lower((email)::text)) WHERE (xoa_luc IS NULL);


--
-- Name: uq_nguoi_dung_ten_dang_nhap; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_nguoi_dung_ten_dang_nhap ON public.nguoi_dung USING btree (lower((ten_dang_nhap)::text)) WHERE ((ten_dang_nhap IS NOT NULL) AND (xoa_luc IS NULL));


--
-- Name: uq_phien_ban_tep_storage; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_phien_ban_tep_storage ON public.phien_ban_tep USING btree (storage_driver, COALESCE(storage_bucket, ''::character varying), storage_key) WHERE (xoa_luc IS NULL);


--
-- Name: uq_phien_khach_token; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_phien_khach_token ON public.phien_khach USING btree (token_hash);


--
-- Name: uq_su_dung_han_muc_nguoi_dung; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_su_dung_han_muc_nguoi_dung ON public.su_dung_han_muc USING btree (nguoi_dung_id, ma_hanh_dong, don_vi, ky_bat_dau, ky_ket_thuc) WHERE (nguoi_dung_id IS NOT NULL);


--
-- Name: uq_su_dung_han_muc_phien_khach; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_su_dung_han_muc_phien_khach ON public.su_dung_han_muc USING btree (phien_khach_id, ma_hanh_dong, don_vi, ky_bat_dau, ky_ket_thuc) WHERE (phien_khach_id IS NOT NULL);


--
-- Name: buoc_cong_viec trg_buoc_cong_viec_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_buoc_cong_viec_updated_at BEFORE UPDATE ON public.buoc_cong_viec FOR EACH ROW EXECUTE FUNCTION public.fn_cap_nhat_updated_at();


--
-- Name: chinh_sach_han_muc trg_chinh_sach_han_muc_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_chinh_sach_han_muc_updated_at BEFORE UPDATE ON public.chinh_sach_han_muc FOR EACH ROW EXECUTE FUNCTION public.fn_cap_nhat_updated_at();


--
-- Name: chuyen_doi trg_chuyen_doi_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_chuyen_doi_updated_at BEFORE UPDATE ON public.chuyen_doi FOR EACH ROW EXECUTE FUNCTION public.fn_cap_nhat_updated_at();


--
-- Name: cong_viec trg_cong_viec_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_cong_viec_updated_at BEFORE UPDATE ON public.cong_viec FOR EACH ROW EXECUTE FUNCTION public.fn_cap_nhat_updated_at();


--
-- Name: dang_ky_goi trg_dang_ky_goi_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_dang_ky_goi_updated_at BEFORE UPDATE ON public.dang_ky_goi FOR EACH ROW EXECUTE FUNCTION public.fn_cap_nhat_updated_at();


--
-- Name: goi_dich_vu trg_goi_dich_vu_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_goi_dich_vu_updated_at BEFORE UPDATE ON public.goi_dich_vu FOR EACH ROW EXECUTE FUNCTION public.fn_cap_nhat_updated_at();


--
-- Name: ma_xac_thuc trg_ma_xac_thuc_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_ma_xac_thuc_updated_at BEFORE UPDATE ON public.ma_xac_thuc FOR EACH ROW EXECUTE FUNCTION public.fn_cap_nhat_updated_at();


--
-- Name: nguoi_dung trg_nguoi_dung_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_nguoi_dung_updated_at BEFORE UPDATE ON public.nguoi_dung FOR EACH ROW EXECUTE FUNCTION public.fn_cap_nhat_updated_at();


--
-- Name: phien_ban_tep trg_phien_ban_tep_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_phien_ban_tep_updated_at BEFORE UPDATE ON public.phien_ban_tep FOR EACH ROW EXECUTE FUNCTION public.fn_cap_nhat_updated_at();


--
-- Name: phien_dang_nhap trg_phien_dang_nhap_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_phien_dang_nhap_updated_at BEFORE UPDATE ON public.phien_dang_nhap FOR EACH ROW EXECUTE FUNCTION public.fn_cap_nhat_updated_at();


--
-- Name: phien_khach trg_phien_khach_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_phien_khach_updated_at BEFORE UPDATE ON public.phien_khach FOR EACH ROW EXECUTE FUNCTION public.fn_cap_nhat_updated_at();


--
-- Name: su_dung_han_muc trg_su_dung_han_muc_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_su_dung_han_muc_updated_at BEFORE UPDATE ON public.su_dung_han_muc FOR EACH ROW EXECUTE FUNCTION public.fn_cap_nhat_updated_at();


--
-- Name: tep trg_tep_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_tep_updated_at BEFORE UPDATE ON public.tep FOR EACH ROW EXECUTE FUNCTION public.fn_cap_nhat_updated_at();


--
-- Name: buoc_cong_viec fk_buoc_cong_viec_cong_viec; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.buoc_cong_viec
    ADD CONSTRAINT fk_buoc_cong_viec_cong_viec FOREIGN KEY (cong_viec_id) REFERENCES public.cong_viec(id) ON DELETE CASCADE;


--
-- Name: chinh_sach_han_muc fk_chinh_sach_han_muc_goi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chinh_sach_han_muc
    ADD CONSTRAINT fk_chinh_sach_han_muc_goi FOREIGN KEY (goi_dich_vu_id) REFERENCES public.goi_dich_vu(id) ON DELETE CASCADE;


--
-- Name: chuyen_doi fk_chuyen_doi_buoc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chuyen_doi
    ADD CONSTRAINT fk_chuyen_doi_buoc FOREIGN KEY (buoc_cong_viec_id) REFERENCES public.buoc_cong_viec(id) ON DELETE SET NULL;


--
-- Name: chuyen_doi fk_chuyen_doi_cong_viec; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chuyen_doi
    ADD CONSTRAINT fk_chuyen_doi_cong_viec FOREIGN KEY (cong_viec_id) REFERENCES public.cong_viec(id) ON DELETE CASCADE;


--
-- Name: chuyen_doi fk_chuyen_doi_phien_ban_ket_qua; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chuyen_doi
    ADD CONSTRAINT fk_chuyen_doi_phien_ban_ket_qua FOREIGN KEY (phien_ban_ket_qua_id) REFERENCES public.phien_ban_tep(id) ON DELETE SET NULL;


--
-- Name: chuyen_doi fk_chuyen_doi_phien_ban_nguon; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chuyen_doi
    ADD CONSTRAINT fk_chuyen_doi_phien_ban_nguon FOREIGN KEY (phien_ban_nguon_id) REFERENCES public.phien_ban_tep(id) ON DELETE SET NULL;


--
-- Name: cong_viec fk_cong_viec_nguoi_dung; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cong_viec
    ADD CONSTRAINT fk_cong_viec_nguoi_dung FOREIGN KEY (nguoi_dung_id) REFERENCES public.nguoi_dung(id) ON DELETE SET NULL;


--
-- Name: cong_viec fk_cong_viec_phien_ban_ket_qua; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cong_viec
    ADD CONSTRAINT fk_cong_viec_phien_ban_ket_qua FOREIGN KEY (phien_ban_ket_qua_id) REFERENCES public.phien_ban_tep(id) ON DELETE SET NULL;


--
-- Name: cong_viec fk_cong_viec_phien_ban_nguon; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cong_viec
    ADD CONSTRAINT fk_cong_viec_phien_ban_nguon FOREIGN KEY (phien_ban_nguon_id) REFERENCES public.phien_ban_tep(id) ON DELETE SET NULL;


--
-- Name: cong_viec fk_cong_viec_phien_khach; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cong_viec
    ADD CONSTRAINT fk_cong_viec_phien_khach FOREIGN KEY (phien_khach_id) REFERENCES public.phien_khach(id) ON DELETE SET NULL;


--
-- Name: cong_viec fk_cong_viec_tep_ket_qua; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cong_viec
    ADD CONSTRAINT fk_cong_viec_tep_ket_qua FOREIGN KEY (tep_ket_qua_id) REFERENCES public.tep(id) ON DELETE SET NULL;


--
-- Name: cong_viec fk_cong_viec_tep_nguon; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cong_viec
    ADD CONSTRAINT fk_cong_viec_tep_nguon FOREIGN KEY (tep_nguon_id) REFERENCES public.tep(id) ON DELETE SET NULL;


--
-- Name: dang_ky_goi fk_dang_ky_goi_goi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dang_ky_goi
    ADD CONSTRAINT fk_dang_ky_goi_goi FOREIGN KEY (goi_dich_vu_id) REFERENCES public.goi_dich_vu(id) ON DELETE RESTRICT;


--
-- Name: dang_ky_goi fk_dang_ky_goi_nguoi_dung; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dang_ky_goi
    ADD CONSTRAINT fk_dang_ky_goi_nguoi_dung FOREIGN KEY (nguoi_dung_id) REFERENCES public.nguoi_dung(id) ON DELETE CASCADE;


--
-- Name: lich_su fk_lich_su_cong_viec; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lich_su
    ADD CONSTRAINT fk_lich_su_cong_viec FOREIGN KEY (cong_viec_id) REFERENCES public.cong_viec(id) ON DELETE SET NULL;


--
-- Name: lich_su fk_lich_su_nguoi_dung; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lich_su
    ADD CONSTRAINT fk_lich_su_nguoi_dung FOREIGN KEY (nguoi_dung_id) REFERENCES public.nguoi_dung(id) ON DELETE SET NULL;


--
-- Name: lich_su fk_lich_su_phien_ban_tep; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lich_su
    ADD CONSTRAINT fk_lich_su_phien_ban_tep FOREIGN KEY (phien_ban_tep_id) REFERENCES public.phien_ban_tep(id) ON DELETE SET NULL;


--
-- Name: lich_su fk_lich_su_phien_khach; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lich_su
    ADD CONSTRAINT fk_lich_su_phien_khach FOREIGN KEY (phien_khach_id) REFERENCES public.phien_khach(id) ON DELETE SET NULL;


--
-- Name: lich_su fk_lich_su_tep; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lich_su
    ADD CONSTRAINT fk_lich_su_tep FOREIGN KEY (tep_id) REFERENCES public.tep(id) ON DELETE SET NULL;


--
-- Name: ma_xac_thuc fk_ma_xac_thuc_nguoi_dung; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ma_xac_thuc
    ADD CONSTRAINT fk_ma_xac_thuc_nguoi_dung FOREIGN KEY (nguoi_dung_id) REFERENCES public.nguoi_dung(id) ON DELETE SET NULL;


--
-- Name: nhat_ky fk_nhat_ky_buoc_cong_viec; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nhat_ky
    ADD CONSTRAINT fk_nhat_ky_buoc_cong_viec FOREIGN KEY (buoc_cong_viec_id) REFERENCES public.buoc_cong_viec(id) ON DELETE SET NULL;


--
-- Name: nhat_ky fk_nhat_ky_cong_viec; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nhat_ky
    ADD CONSTRAINT fk_nhat_ky_cong_viec FOREIGN KEY (cong_viec_id) REFERENCES public.cong_viec(id) ON DELETE SET NULL;


--
-- Name: nhat_ky fk_nhat_ky_nguoi_dung; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nhat_ky
    ADD CONSTRAINT fk_nhat_ky_nguoi_dung FOREIGN KEY (nguoi_dung_id) REFERENCES public.nguoi_dung(id) ON DELETE SET NULL;


--
-- Name: nhat_ky fk_nhat_ky_phien_khach; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nhat_ky
    ADD CONSTRAINT fk_nhat_ky_phien_khach FOREIGN KEY (phien_khach_id) REFERENCES public.phien_khach(id) ON DELETE SET NULL;


--
-- Name: nhat_ky fk_nhat_ky_tep; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nhat_ky
    ADD CONSTRAINT fk_nhat_ky_tep FOREIGN KEY (tep_id) REFERENCES public.tep(id) ON DELETE SET NULL;


--
-- Name: phien_ban_tep fk_phien_ban_tep_cha; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phien_ban_tep
    ADD CONSTRAINT fk_phien_ban_tep_cha FOREIGN KEY (phien_ban_cha_id) REFERENCES public.phien_ban_tep(id) ON DELETE SET NULL;


--
-- Name: phien_ban_tep fk_phien_ban_tep_cong_viec_tao; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phien_ban_tep
    ADD CONSTRAINT fk_phien_ban_tep_cong_viec_tao FOREIGN KEY (cong_viec_tao_id) REFERENCES public.cong_viec(id) ON DELETE SET NULL;


--
-- Name: phien_ban_tep fk_phien_ban_tep_tep; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phien_ban_tep
    ADD CONSTRAINT fk_phien_ban_tep_tep FOREIGN KEY (tep_id) REFERENCES public.tep(id) ON DELETE CASCADE;


--
-- Name: phien_dang_nhap fk_phien_dang_nhap_nguoi_dung; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phien_dang_nhap
    ADD CONSTRAINT fk_phien_dang_nhap_nguoi_dung FOREIGN KEY (nguoi_dung_id) REFERENCES public.nguoi_dung(id) ON DELETE CASCADE;


--
-- Name: su_dung_han_muc fk_su_dung_han_muc_chinh_sach; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.su_dung_han_muc
    ADD CONSTRAINT fk_su_dung_han_muc_chinh_sach FOREIGN KEY (chinh_sach_han_muc_id) REFERENCES public.chinh_sach_han_muc(id) ON DELETE SET NULL;


--
-- Name: su_dung_han_muc fk_su_dung_han_muc_nguoi_dung; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.su_dung_han_muc
    ADD CONSTRAINT fk_su_dung_han_muc_nguoi_dung FOREIGN KEY (nguoi_dung_id) REFERENCES public.nguoi_dung(id) ON DELETE CASCADE;


--
-- Name: su_dung_han_muc fk_su_dung_han_muc_phien_khach; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.su_dung_han_muc
    ADD CONSTRAINT fk_su_dung_han_muc_phien_khach FOREIGN KEY (phien_khach_id) REFERENCES public.phien_khach(id) ON DELETE CASCADE;


--
-- Name: tep fk_tep_nguoi_dung; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tep
    ADD CONSTRAINT fk_tep_nguoi_dung FOREIGN KEY (nguoi_dung_id) REFERENCES public.nguoi_dung(id) ON DELETE SET NULL;


--
-- Name: tep fk_tep_phien_khach; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tep
    ADD CONSTRAINT fk_tep_phien_khach FOREIGN KEY (phien_khach_id) REFERENCES public.phien_khach(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict Om8VEeVKmnGBcOmNUgdNyEHFm7O67qxv3Hb05q2OqwDNix1CfdD1Kc0MWud6bJU

