'use strict';
const express = require('express');
const compression = require('compression');
const cookieParser = require('cookie-parser');
const session = require('express-session');
const { engine } = require('express-handlebars');
const appConfig = require('./config/app.config');
const sessionConfig = require('./config/session.config');
const viewConfig = require('./config/view.config');
const assetConfig = require('./config/asset.config');
const { layViewHelpers } = require('./core/views/view-helper');
const { taoViewContext } = require('./core/views/view-context');
const { authMiddleware } = require('./middlewares/auth.middleware');
const { csrfMiddleware } = require('./middlewares/csrf.middleware');
const { flashMiddleware } = require('./middlewares/flash.middleware');
const { requestContextMiddleware } = require('./middlewares/request-context.middleware');
const { securityMiddleware } = require('./middlewares/security.middleware');
const { notFoundMiddleware } = require('./middlewares/not-found.middleware');
const { errorMiddleware } = require('./middlewares/error.middleware');
const app = express();

if (appConfig.trustProxy !== false) { app.set('trust proxy', appConfig.trustProxy); }
app.disable('x-powered-by');
app.engine(viewConfig.engineName, engine({ extname: viewConfig.extname, defaultLayout: viewConfig.defaultLayout, layoutsDir: viewConfig.layoutsDir, partialsDir: viewConfig.partialsDir, helpers: layViewHelpers() }));
app.set('view engine', viewConfig.engineName);
app.set('views', viewConfig.viewsDir);
app.use(requestContextMiddleware);
app.use(securityMiddleware);
app.use(compression());
app.use(assetConfig.urlPrefix, express.static(assetConfig.rootDir, { maxAge: assetConfig.maxAge, immutable: assetConfig.immutable, index: assetConfig.index, fallthrough: assetConfig.fallthrough }));
app.use(cookieParser());
app.use(session(sessionConfig));
app.use(flashMiddleware);
app.use(express.json({ limit: appConfig.jsonLimit }));
app.use(express.urlencoded({ extended: true, limit: appConfig.urlencodedLimit }));
app.use(csrfMiddleware);
app.use(authMiddleware);
app.get('/', (req, res) => res.render('pages/trang-chu', taoViewContext(req, res, { page: { title: 'Transform Platform' } })));
app.use(notFoundMiddleware);
app.use(errorMiddleware);

module.exports = app;